[build]
command = "cp netlify-requirements.txt requirements.txt"
functions = "netlify/functions"
publish = "."

[functions]
python_runtime = "python3.9"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200