services:
  - type: web
    name: gravilog
    env: python
    plan: free
    buildCommand: mv pyproject.toml pyproject.toml.bak && pip install -r render-requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT