services:
  - type: web
    name: gravitlog
    env: python
    buildCommand: pip install -r render-requirements.txt
    startCommand: python main.py
    plan: free
    environmentGroup: main
    region: oregon
    branch: main
    rootDir: .
    runtime: python
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: true
      - key: RENDER
        value: true